import { ILang, interest } from "../types/Auth/auth"


export const dictionary = {
  en: {
    autoSearch: 'Auto-match',
    manuallySearch: 'Explore manually',
    letterOnTheWay: 'Letter on the way',
    changeLang: 'Change language to english',
    appLang: 'Application language',
    penpals: 'Penpals',
    friends: 'Friends',
    helloWorld: 'Share your interests with the world!',
    letsStart: 'Let\'s start',
    alredyHaveAcc: 'Already have an account? Login',
    next: 'Next',
    sex: 'Sex',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    birthday: 'Birthday',
    enterDate: 'Please enter the correct date (YYYY-MM-DD)',
    nickName: 'Nickname',
    required: 'Field is required',
    selectInterests: 'Select topics that interest you.',
    interestsHelp: 'They will help you to find friends with common interests.',
    'Language learning': 'Language learning',
    'Movies': 'Movies',
    'Pets': 'Pets',
    'Nature': 'Nature',
    'Adventures': 'Adventures',
    'Climate': 'Climate',
    'Handmade': 'Handmade',
    'Writing': 'Writing',
    'Beauty': 'Beauty',
    'Makeup': 'Makeup',
    'Fitness': 'Fitness',
    'Cosplay': 'Cosplay',
    'Dancing': 'Dancing',
    'Languages': 'Languages',
    'You can add more than one': 'You can add more than one',
    add: 'Add',
    'Language Proficiency': 'Language Proficiency',
    Interested: 'Interested',
    Beginning: 'Beginning',
    Average: 'Average',
    Advanced: 'Advanced',
    Fluency: 'Fluency',
    'Native language': 'Native language',
    updateProficiency: 'Update your language proficiency',
    deleteLang: 'Delete language',
    cancel: 'Cancel',
    'Where are you?': 'Where are you?',
    deliveryTimeDepens: 'Delivery time for letters depends on where you and your friend live.',
    determineGeo: 'Determine by geolocation',
    determineIp: 'Determine by IP-address',
    condolences: 'My condolences, you are from',
    hello: 'Hello',
    helloUkraine: 'Good evening, you are from Ukraine!',
    email: 'Email',
    enterCorrectEmail: 'Enter correct email',
    enterCorrectPassword: 'Password must be longer than 6 characters',
    password: 'Password',
    successfulSignUp: 'Registration completed successfully!',
    confirmEmail: 'Confirm email and sign in',
    gotoLogin: 'Go to login page',
    welcome: 'Welcome!',
    signIn: 'Sign In'
  },
  ua: {
    autoSearch: 'Автопошук',
    manuallySearch: 'Шукати вручну',
    letterOnTheWay: 'Лист у дорозі',
    changeLang: 'Змінити мову на українську',
    appLang: 'Мова програми',
    penpals: 'Друзі по листуванню',
    friends: 'Друзі',
    helloWorld: 'Поділіться своїми інтересами зі світом!',
    letsStart: 'Давайте почнемо',
    alredyHaveAcc: 'Вже є акаунт? Увійти',
    next: 'Далі',
    sex: 'Стать',
    male: 'Чоловічий',
    female: 'Жіноча',
    other: 'Інший',
    birthday: 'День народження',
    enterDate: 'Будь ласка, введіть правильну дату (YYYY-MM-DD)',
    nickName: 'Псевдонім',
    required: 'Поле обов\'язкове',
    selectInterests: 'Виберіть теми, які вас цікавлять.',
    interestsHelp: 'Вони допоможуть знайти друзів зі спільними інтересами.',
    'Language learning': 'Вивчення мови',
    'Movies': 'Фільми',
    'Pets': 'Домашні тварини',
    'Nature': 'Природа',
    'Adventures': 'Пригоди',
    'Climate': 'Клімат',
    'Handmade': 'Ручна робота',
    'Writing': "Написання",
    'Beauty': 'Краса',
    'Makeup': 'Макіяж',
    'Fitness': "Фітнес",
    'Cosplay': "Косплей",
    'Dancing': "Танці",
    'Languages': "Мови",
    'You can add more than one': 'Ви можете додати більше однієї',
    add: 'Додати',
    'Language Proficiency': 'Рівень володіння мовою',
    Interested: 'Цікавить',
    Beginning: 'Початківець',
    Average: 'Середній',
    Advanced: 'Вище середнього',
    Fluency: 'Вільне володіння',
    'Native language': 'Рідна мова',
    updateProficiency: 'Оновити рівень володіння мовою',
    deleteLang: 'Видалити мову',
    cancel: 'Відміна',
    'Where are you?': 'Звідки ви?',
    deliveryTimeDepens: 'Час доставки листів залежить від того, де ви та ваш друг мешкаєте.',
    determineGeo: 'Визначити по геолокації',
    determineIp: 'Визначити по IP-адресі',
    condolences: 'Співчуваю, ви з',
    hello: 'Hello',
    helloUkraine: 'Доброго вечора, ви з України!',
    email: 'Електронна пошта',
    enterCorrectEmail: 'Введіть коректну пошту',
    enterCorrectPassword: 'Пароль повинен бути довшим за 6 символів',
    password: 'Пароль',
    successfulSignUp: 'Реєстрація пройшла успішно!',
    confirmEmail: 'Підтвердіть пошту та увійдіть',
    gotoLogin: 'Перейти на сторінку входу',
    welcome: 'Ласкаво просимо!',
    signIn: 'Увійти'
  }
}

export const interestArr: interest[] = ['Language learning', 'Movies', 'Pets', 'Nature', 'Adventures', 'Climate', 'Handmade', 'Writing', 'Beauty', 'Makeup', 'Fitness', 'Cosplay', 'Dancing']

export type langType = 'en' | 'ua' | 'de' | 'es' | 'it' | 'fr'

export const writingLang: ILang[] = [
  { name: 'English', engName: 'English', isSelected: false, level: 0, code: 'en' },
  { name: 'Українська', engName: 'Ukrainian', isSelected: false, level: 0, code: 'ua' },
  { name: 'Français', engName: 'French', isSelected: false, level: 0, code: 'fr' },
  { name: 'Deutsch', engName: 'German', isSelected: false, level: 0, code: 'de' },
  { name: 'Italiano', engName: 'Italian', isSelected: false, level: 0, code: 'it' },
  { name: 'Español', engName: 'Spanish', isSelected: false, level: 0, code: 'es' },
]
